Library/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;

namespace Library.Controllers
{
  public class AuthorsController : Controller
  {
    private readonly LibraryContext _db;
    public AuthorsController(LibraryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Author> model = _db.Authors.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }
    
    [HttpPost]
    public ActionResult Create(Author author)
    {
      _db.Authors.Add(author);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Details(int id)
    {
      var thisAuthor = _db.Authors
        .Include(a => a.JoinEntities)
        .ThenInclude(join => join.Book)
        .FirstOrDefault(a => a.AuthorId == id);
      var rList = _db.Authors.ToList();
      rList.Reverse();
      ViewBag.Previous = rList.FirstOrDefault(a => a.AuthorId < id);
      ViewBag.Next = _db.Authors.FirstOrDefault(a => a.AuthorId > id);
      return View(thisAuthor);
    }
    public ActionResult Edit(int id)
    {
      var thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }
    [HttpPost]
    public ActionResult Edit(Author author)
    {
      _db.Entry(author).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddBook(int id)
    {
      List<Book> books = _db.Books.ToList();
      List<Book> BooksList = _db.Books.ToList();
      var a = _db.AuthorBook.Where(book => book.AuthorId == id);
      foreach(AuthorBook w in a)
      {
        foreach(Book book in books)
        {
          if (book.BookId == w.BookId)
          {
            BooksList.Remove(book);
          }
        }
      }
      ViewBag.num = BooksList.Count;
      ViewBag.BookId = new SelectList(BooksList, "BookId", "Title");
      var thisAuthor = _db.Authors.FirstOrDefault(a => a.AuthorId == id);
      return View(thisAuthor);
    }

    [HttpPost]
    public ActionResult AddBook(Author author, int BookId)
    {
      if (BookId != 0 && !_db.AuthorBook.Any(f => f.AuthorId == author.AuthorId && f.BookId == BookId))
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = author.AuthorId, BookId = BookId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
      
    }
    
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisAuthor = _db.Authors.FirstOrDefault(c => c.AuthorId == id);
      _db.Authors.Remove(thisAuthor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Library/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  
  public class BooksController : Controller
  {
    private readonly LibraryContext _db;

    public BooksController(LibraryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Books.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Book book, int AuthorId)
    {
      _db.Books.Add(book);
      _db.SaveChanges();
      if (AuthorId != 0)
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
        _db.Copies.Add(new Copy() {BookId = book.BookId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisBook = _db.Books
        .Include(b => b.JoinEntities)
        .ThenInclude(join => join.Author)
        .FirstOrDefault(b => b.BookId == id);
      var rList = _db.Books.ToList();
      rList.Reverse();
      ViewBag.Previous = rList.FirstOrDefault(a => a.BookId < id);
      ViewBag.Next = _db.Books.FirstOrDefault(a => a.BookId > id);
      return View(thisBook);
    }

    public ActionResult Edit(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(book => book.BookId == id);
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
      return View(thisBook);
    }

    [HttpPost]
    public ActionResult Edit(Book book, int AuthorId)
    {
      if (AuthorId != 0)
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
      }
      _db.Entry(book).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAuthor(int id)
    {
      List<Author> authors = _db.Authors.ToList();
      List<Author> AuthorsList = _db.Authors.ToList();
      var a = _db.AuthorBook.Where(author => author.BookId == id);
      foreach(AuthorBook w in a)
      {
        foreach(Author author in authors)
        {
          if (author.AuthorId == w.AuthorId)
          {
            AuthorsList.Remove(author);
          }
        }
      }
      ViewBag.num = AuthorsList.Count;
      ViewBag.AuthorId = new SelectList(AuthorsList, "AuthorId", "Name");
      var thisBook = _db.Books.FirstOrDefault(b => b.BookId == id);
      return View(thisBook);
    }

    [HttpPost]
    public ActionResult AddAuthor(Book book, int AuthorId)
    {
      if (AuthorId != 0 && !_db.AuthorBook.Any(f => f.AuthorId == AuthorId && f.BookId == book.BookId))
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(book => book.BookId == id);
      return View(thisBook);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(book => book.BookId == id);
      _db.Books.Remove(thisBook);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteAuthor(int joinId)
    {
      var joinEntry = _db.AuthorBook.FirstOrDefault(entry => entry.AuthorBookId == joinId);
      _db.AuthorBook.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Library/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  public class HomeController : Controller
  {
    public readonly LibraryContext _db;
    public HomeController(LibraryContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult Search(string Search)
    {
      var authors = _db.Authors.Where(author => (author.Name.Contains(Search) || (author.Name == Search))).ToList();
      ViewBag.Authors = authors;
      return View();
    }

    public ActionResult Heh()
    {
      return View();
    }
  }
}

Library/Controllers/PatronsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;
using System;

namespace Library.Controllers
{
  [Authorize]
  public class PatronsController : Controller
  {
    private readonly LibraryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public PatronsController(UserManager<ApplicationUser> userManager, LibraryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Patrons.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.CopyId = new SelectList(_db.Copies, "CopyId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Patron patron, int CopyId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      patron.User = currentUser;
      _db.Patrons.Add(patron);
      _db.SaveChanges();
      if (CopyId != 0)
      {
        _db.Checkout.Add(new Checkout() { CopyId = CopyId, PatronId = patron.PatronId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    { 
      ViewBag.Test = _db.Copies.ToList().Count;
      Patron thisPatron = _db.Patrons
        .Include(patron => patron.JoinEntitiesOne)
        .ThenInclude(join => join.Book)
        .FirstOrDefault(patron => patron.PatronId == id);
      ViewBag.Books = _db.Books
        .Include(b => b.JoinEntitiesOne)
        .FirstOrDefault(c => c.BookId == c.BookId);
      return View(thisPatron);
    }

    public ActionResult Edit(int id)
    {
      var thisPatron = _db.Patrons.FirstOrDefault(patron => patron.PatronId == id);
      ViewBag.CopyId = new SelectList(_db.Copies, "CopyId", "Name");
      return View(thisPatron);
    }

    [HttpPost]
    public ActionResult Edit(Patron patron, int CopyId)
    {
      if (CopyId != 0)
      {
        _db.Checkout.Add(new Checkout() { CopyId = CopyId, PatronId = patron.PatronId });
      }
      _db.Entry(patron).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
      public ActionResult CheckOut(int id)
    {
      var thisPatron = _db.Patrons.FirstOrDefault(patron => patron.PatronId == id);
      ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
      return View(thisPatron);
    }

    [HttpPost]
    public ActionResult CheckOut(Book book, int PatronId)
    {
      if (book.BookId != 0)
      {
        _db.Copies.Add(new Copy() { BookId = book.BookId, PatronId = PatronId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    // [HttpPost]
    // public ActionResult CheckIn(int CopyId)
    // {
    //   Copy target = _db.Copies.FirstOrDefault(copy => copy.CopyId == CopyId);
    //   _db.Entry(target).State = EntityState.Modified;
    //   _db.SaveChanges(); 
    //   return RedirectToAction("Details", new {id = patronId});
    // }

    public ActionResult Delete(int CopyId)
    {
      var thisCopy = _db.Copies.FirstOrDefault(c => c.CopyId == CopyId);
      //ViewBag.test = _db.Books.FirstOrDefault(b => b.BookId == thisCopy.BookId);
      ViewBag.test = CopyId;
      Console.WriteLine("delete get post");
      return View(thisCopy);
    }

    // [HttpPost, ActionName("Delete")]
    // public ActionResult DeleteConfirmed(int id)
    // {
    //   var thisPatron = _db.Patrons.FirstOrDefault(p => p.PatronId == id);
    //   _db.Patrons.Remove(thisPatron);
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }

    [HttpPost]
    public ActionResult Delete(int CopyId, string test)
    {
      var joinEntry = _db.Copies.FirstOrDefault(entry => entry.CopyId == CopyId);
      Console.WriteLine("ddddelete post");
      _db.Copies.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Library/Views/Home/Heh.cshtml
@{
  Layout = "_Layout";
}

<img src="https://bestlifeonline.com/wp-content/uploads/sites/3/2018/04/Trapped-in-Toilet.jpg?quality=82&strip=all" width="600" height="600" />

Library/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@model IEnumerable<Library.Models.Book>

<h1>Welcome to the library!</h1>
<p>@Html.ActionLink("See all books", "Index", "Books")</p> 
<p>@Html.ActionLink("See all authors", "Index", "Authors")</p>
<p>@Html.ActionLink("See all patrons", "Index", "Patrons")</p>
<p>@Html.ActionLink("Search", "Search")</p>
<div id="header">
@if (@User.Identity.Name != null)
{
  <p>@User.Identity.Name</p>
  <p>@Html.ActionLink("My Account", "", "Account")</p>
  @using (Html.BeginForm("LogOff", "Account"))
  {
    <input type="submit" class="btn btn-default" value="Log out" />
  }
}
else
{
  <p>@Html.ActionLink("Register", "Register", "Account")</p>
  <p>@Html.ActionLink("Login", "Login", "Account")</p>
}
</div>

Library/Views/Home/Search.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author

<div class="jumbotron">
  <h1>Search Results</h1>
  <h3><span class="a">S</span><span class="b">e</span><span class="b">e</span><span class="c">r</span><span class="d">c</span><span class="e">h</span> <span class="f">f</span><span class="g">u</span><span class="h">r</span> <span class="i">a</span><span class="j">t</span><span class="k">h</span><span class="l">o</span><span class="m">r</span><span class="n">z</span></h3>
</div>

@using (Html.BeginForm())
{
  @Html.TextBoxFor(model => model.Search)
  <input type="submit" value="Search" />
}
<div class="row">
<button class="btn-warning">A</button><button class="btn-warning">B</button><button class="btn-warning">C</button><button class="btn-success">D</button><button class="btn-warning">E</button><button class="btn-success">F</button><button class="btn-warning">G</button><button class="btn-warning">H</button><button class="btn-warning">I</button><button class="btn-warning">J</button><button class="btn-warning">K</button><button class="btn-warning">L</button><button class="btn-success">M</button><button class="btn-success">@Html.ActionLink("🖕", "Heh", "Home")</button><button class="btn-warning">N</button><button class="btn-warning">O</button><button class="btn-warning">P</button><button class="btn-success">Q</button><button class="btn-warning">R</button><button class="btn-warning">S</button><button class="btn-warning">T</button><button class="btn-warning">U</button><button class="btn-warning">V</button><button class="btn-success">W</button><button class="btn-warning">X</button><button class="btn-success">Y</button><button class="btn-warning">Z</button>
</div>


@if (@ViewBag.Authors.Count == 0)
{
  <img src="https://www.liveabout.com/thmb/1PmsRT79lbMxbS-jV-bHZo9RtSQ=/2399x1799/smart/filters:no_upscale()/RageFaceNo-5ae79bcd3128340037321cb4.jpg" width="240" height="200">
}
else
{
  <h3>Authors from search:</h3>
  @foreach (var authors in ViewBag.Authors)
  {
    <li>@Html.ActionLink($"{authors.Name}", "Details", "Authors", new { id = authors.AuthorId })</li>  
  } 
}